### ISSUE TITLE
Let customer create a new SSH key if he is a new customer.

### ISSUE THREAD

**Issue by nodeloc** [EZSCALE/virtfusion-whmcs-module#1]
Most people is new customer and he have no SSH keys. Because SSH is made in console. In factly new customer even don't have a console account.
So , Could you add a feature to the order form that enables customers to create a new SSH keys, Just look like AWS?

<img width="602" alt="1" src="https://github.com/EZSCALE/virtfusion-whmcs-module/assets/149086144/fd7a716b-c2c8-444f-96d0-0b00f94ace23">
<img width="464" alt="2" src="https://github.com/EZSCALE/virtfusion-whmcs-module/assets/149086144/d30c9129-cd48-4740-9a1e-9bdef0f4a5b4">

Thank you.

**Comment by Prophet731** [comment]
That's a bit out of scope for what this module should do. There is a plan to allow a user to use their existing key that they can paste in if they are a brand new customer but trying to figure out a way to flow it correctly in a order process.
