### ISSUE TITLE
Error While Ordering more than 1 products

### ISSUE THREAD

**Issue by Thakor-Rohan** [EZSCALE/virtfusion-whmcs-module#3]
TypeError: array_key_exists(): Argument #2 ($array) must be of type array, bool given in /home/pro/public_html/modules/servers/VirtFusionDirect/lib/ModuleFunctions.php:139
Stack trace:
#0 /home/pro/public_html/modules/servers/VirtFusionDirect/lib/ModuleFunctions.php(139): array_key_exists('ipv4', true)
#1 /home/pro/public_html/modules/servers/VirtFusionDirect/VirtFusionDirect.php(63): WHMCS\Module\Server\VirtFusionDirect\ModuleFunctions->createAccount(Array)
#2 [internal function]: VirtFusionDirect_CreateAccount(Array)
#3 /home/pro/public_html/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func('VirtFusionDirec...', Array)
#4 /home/pro/public_html/vendor/whmcs/whmcs-foundation/lib/Module/Server.php(0): WHMCS\Module\AbstractModule->call('CreateAccount', Array)
#5 /home/pro/public_html/includes/modulefunctions.php(0): WHMCS\Module\Server->call('CreateAccount', Array)
#6 /home/pro/public_html/vendor/whmcs/whmcs-foundation/lib/Service/Service.php(0): ModuleCallFunction('Create', 47)
#7 /home/pro/public_html/includes/invoicefunctions.php(0): WHMCS\Service\Service->legacyProvision()
#8 /home/pro/public_html/includes/invoicefunctions.php(0): makeHostingPayment(47, Object(WHMCS\Billing\Invoice))
#9 /home/pro/public_html/cart.php(0): processPaidInvoice(38)
#10 {main}

**Comment by Prophet731** [comment]
Can you explain the steps you did for multiple orders? I've had customers make them without an issue.

**Comment by Thakor-Rohan** [comment]
Sure, i just increased cart from 1 to multiple and this error happens, also my theme is lagom, php version 8.1

**Comment by Prophet731** [comment]
Question, do you have a custom option for IPv4 address in the order? Looking over this again, it looks like its providing that value as a boolean instead of a number.

**Comment by Thakor-Rohan** [comment]
Not sure what happened, but a fresh install with the same stuff seems to have done the trick! Everything's working as expected again. Feel free to close this issue if all is good on your end.
